algoritmo "ex07"
//aluna juliana
//Exiba o menu: 1 – Novo cadastro, 2 – Consultar, 3 – Sair. 
//Leia a opção escolhida até que o usuário escolha uma opção válida (1, 2 ou 3), depois informe qual opção foi escolhida. 
var

op:inteiro

inicio
	repita
  limpatela
	escreval("1- Novo Cadastro")
	escreval("2- Consultar")
  escreval("3- Sair")
  leia(op)
  ate (op>=1) e (op<=3)
  
 	escreval("a opção escolhida foi ",op)
 
fimalgoritmo