Algoritmo "ex10"

//aluna Juliana Mafra

var
 n1: real
 n2: real
Inicio
   
    escreval("Digite o numero 1")
    leia(n1)
    escreval("Digite o numero 2")
    leia(n2)
    escreval(n1," + ",n2," = ",n1+n2:8)
    escreval(n1," - ",n2," = ",n1-n2:8)
    escreval(n1," x ",n2," = ",n1*n2:8)
    escreval(n1," ÷ ",n2," = ",n1/n2:8:2)
    escreval(n1," MOD ",n2," = ",n1%n2:8)
    escreval(n1," ^ ",n2," = ",n1^n2:8)
fimalgoritmo
